name: plantify_production

services:

  reactapp:
    build:
      context: ./plantify-react-app
      dockerfile: Dockerfile
      args:
        VITE_SERVER_URL: http://webapi:8081
    container_name: reactapp
    image: reactapp:latest
    depends_on:
      - nodeserver
    ports:
      - "5174:5174"
    networks:
      - plantify-network

networks:
  plantify-network:
    external: true
