name: dev

services:
    frontenddev:
      image: frontend:dev
      build:
        context: .
        dockerfile: .devcontainer/Dockerfile
      container_name: frontenddev
      environment:
        API_URL: http://host.docker.internal:8081
        PORT: 3021
      volumes:
        - .:/workspace
      working_dir: /workspace
      command: sleep infinity
      user: root
      ports:
        - "5173:5173"
        - "3021:3021"