name: plantify_production

services:

  reactapp:
    build:
      context: ./plantify-react-app
      dockerfile: Dockerfile
    container_name: reactapp
    environment:
      VITE_SERVER_URL: http://webapi:8081
      VITE_PORT: 5174
    image: reactapp:latest
    ports:
      - "5174:80"
    networks:
      - plantify-network

networks:
  plantify-network:
    external: true
