name: plantify_production

services:

  nodeserver:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: nodeserver
    image: nodeserver:latest
    environment:
      NODE_ENV: production
      PORT: 5021
      API_URL: http://webapi:8081
    ports:
      - "5021:5021"
    expose:
      - "5021"
    networks:
      - backend

  reactapp:
    build:
      context: ./plantify-react-app
      dockerfile: Dockerfile
      args:
        VITE_SERVER_URL: http://localhost:5021
    container_name: reactapp
    image: reactapp:latest
    depends_on:
      - nodeserver
    ports:
      - "5174:5174"
    networks:
      - backend

networks:
  backend:
    external: true