name: Build and push image

on:
  push:
    branches: [main]
  workflow_dispatch: 

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./plantify-react-app
          file: ./plantify-react-app/Dockerfile
          push: true
          tags: |
               ghcr.io/via-plantify/plantify-frontend/reactapp:latest
               ghcr.io/via-plantify/plantify-frontend/reactapp:${{ github.sha }}
          build-args: |
               VITE_API_URL=${{ secrets.VITE_API_URL }}

